### ISSUE TITLE
Create a link property in titan.xml  to custom output files

### ISSUE THREAD

**Issue by fernandommota** [titan-framework/core#7]
Hello guys,

I would like do some custom in file core / output / login.php.

For now I'm doing this copying the file myApp / core / output / login.php and moving to / var / www / titan / output when has some change.

My suggestion is to create a property in titan.xml like the custom CSS Skin:

```
<skin
		logo="core/interface/image/logo.png"
		icon="core/interface/favicon.ico"
		css-main="core/interface/css/general.css"
		css-top="core/interface/css/top.css"
		css-menu="core/interface/css/menu.css"	
		css-login="core/interface/css/logon.css"
	/>

<output
		login="core/output/login.php"
	/>
```

In other words the idea is do something like this:
`
sudo ln -s /var/www/app/core/output/login.php /var/www/titan/output/login.php
`

Regards

**Comment by carromeu** [comment]
Hi Maia,

The right way for made this, is copy this file (output/login.php) to root of instance. Because this reason, Titan does not have a 'index.php'. You can add a login box on your owned 'index.php' and authorize user. This a typically custom login page (a modified copy of output/login.php to index.php):

http://rastreabilidade.cnabrasil.org.br/

Kind regards,

Camilo

**Comment by fernandommota** [comment]
Hi Camilo,

thanks, works like a charm!!

So, the right way to map this entries in titan.xml is?!

```
<titan-configuration
	url="http://myDomain.com/app"
	login-url="http://myDomain.com/app?"
```

The symbol "?" is because the message "&message=Deslogado com sucesso!" when user Logoff.

**Comment by fernandommota** [comment]
updating:

```
       url="http://myDomain.com/app"
	login-url="https://myDomain.com/app/index.php?target=login"
```
